### ISSUE TITLE
Being maintained?

### ISSUE THREAD

**Issue by russel** [kchmck/rtlsdr_sys.rs#1]
Is this project being maintained or is it now left by the wayside.

I am trying to choose between https://github.com/jpoirier/rust-rtlsdr, https://github.com/adamgreig/rtlsdr-rs  and https://github.com/kchmck/rtlsdr_sys.rs as a possible choice for a Rust rewrite of some C code that uses librtlsdr.

**Comment by kchmck** [comment]
Hi @russel, I'm using this in an [active project](https://github.com/kchmck/p25rx), so it's being maintained. I guess I haven't had to make many changes since I haven't had any problems with the bindings, but I'll accept pull requests if there are any updates needed
